"""
Routes Super-Admin - Configuration Plateforme
==============================================

Gestion de la configuration globale de la plateforme SaaS.
"""

from flask import request, jsonify, g
from app.routes.superadmin import superadmin_bp
from app.routes.superadmin.auth import superadmin_required, superadmin_permission_required
from app.models import PlatformConfig
from app import db
from datetime import datetime
import logging

logger = logging.getLogger(__name__)


@superadmin_bp.route('/config', methods=['GET'])
@superadmin_required
def get_platform_config():
    """Récupère la configuration de la plateforme"""
    config = PlatformConfig.get_config()
    return jsonify(config.to_dict(include_sensitive=True))


@superadmin_bp.route('/config', methods=['PUT'])
@superadmin_permission_required('config.write')
def update_platform_config():
    """
    Met à jour la configuration de la plateforme
    
    Body: Tous les champs de PlatformConfig
    """
    config = PlatformConfig.get_config()
    data = request.get_json()
    
    # Mettre à jour les champs
    updatable_fields = [
        'platform_name', 'platform_logo', 'platform_favicon',
        'support_email', 'support_phone',
        'website_url', 'terms_url', 'privacy_url',
        'system_email_from', 'system_email_name',
        'default_trial_days', 'max_tenants', 'registration_enabled',
        'maintenance_mode', 'maintenance_message',
        'settings'
    ]
    
    for field in updatable_fields:
        if field in data:
            setattr(config, field, data[field])
    
    config.updated_by = g.superadmin.id
    db.session.commit()
    
    logger.info(f"Platform config updated by {g.superadmin.email}")
    
    return jsonify(config.to_dict())


@superadmin_bp.route('/config/maintenance', methods=['POST'])
@superadmin_permission_required('config.write')
def toggle_maintenance_mode():
    """
    Active/désactive le mode maintenance
    
    Body:
        - enabled: true/false
        - message: Message de maintenance (optionnel)
    """
    config = PlatformConfig.get_config()
    data = request.get_json()
    
    config.maintenance_mode = data.get('enabled', False)
    if 'message' in data:
        config.maintenance_message = data['message']
    
    config.updated_by = g.superadmin.id
    db.session.commit()
    
    status = 'activé' if config.maintenance_mode else 'désactivé'
    logger.warning(f"Maintenance mode {status} by {g.superadmin.email}")
    
    return jsonify({
        'maintenance_mode': config.maintenance_mode,
        'message': config.maintenance_message
    })


@superadmin_bp.route('/config/webhook-secret', methods=['POST'])
@superadmin_permission_required('config.write')
def regenerate_webhook_secret():
    """Régénère le secret des webhooks"""
    import secrets
    
    config = PlatformConfig.get_config()
    config.webhook_secret = secrets.token_urlsafe(32)
    config.updated_by = g.superadmin.id
    db.session.commit()
    
    logger.info(f"Webhook secret regenerated by {g.superadmin.email}")
    
    return jsonify({
        'webhook_secret': config.webhook_secret,
        'message': 'Secret régénéré. Mettez à jour vos intégrations.'
    })


@superadmin_bp.route('/config/public', methods=['GET'])
def get_public_config():
    """
    Configuration publique (pas d'auth requise)
    Utilisée par les pages de login/register
    """
    config = PlatformConfig.get_config()
    
    return jsonify({
        'platform_name': config.platform_name,
        'platform_logo': config.platform_logo,
        'support_email': config.support_email,
        'terms_url': config.terms_url,
        'privacy_url': config.privacy_url,
        'registration_enabled': config.registration_enabled,
        'maintenance_mode': config.maintenance_mode,
        'maintenance_message': config.maintenance_message if config.maintenance_mode else None
    })


# ==================== Initialisation ====================

def init_platform_config():
    """Initialise la configuration par défaut si elle n'existe pas"""
    config = PlatformConfig.query.first()
    if not config:
        config = PlatformConfig(
            id='platform-config-singleton',
            platform_name='Express Cargo SaaS',
            support_email='support@expresscargo.com',
            default_trial_days=14,
            registration_enabled=True
        )
        db.session.add(config)
        db.session.commit()
        logger.info("Platform config initialized")
    return config


def init_primary_superadmin(email: str, password: str, first_name: str = 'Super', last_name: str = 'Admin'):
    """
    Crée le super-admin primaire s'il n'existe pas
    À appeler au premier démarrage
    """
    from app.models import SuperAdmin
    
    existing = SuperAdmin.query.filter_by(is_primary=True).first()
    if existing:
        return existing
    
    admin = SuperAdmin(
        email=email,
        first_name=first_name,
        last_name=last_name,
        is_primary=True,
        is_active=True,
        permissions=['*']  # Toutes les permissions
    )
    admin.set_password(password)
    
    db.session.add(admin)
    db.session.commit()
    
    logger.info(f"Primary super-admin created: {email}")
    return admin
